Repository Linux4Yourself/book, pull requests merged in 2021-05, with the labels that each got.

#138 Coreuils
  docs/_sidebar.md
  docs/build-temp-system/coreutils.md
Labels: enhancement

#141 Book-wide fixes
  docs/build-temp-system/bash.md
  docs/build-temp-system/coreutils.md
  docs/build-temp-system/diffutils.md
  docs/build-temp-system/glibc.md
  docs/build-temp-system/libstdc.md
  docs/build-temp-system/linux-headers.md
  docs/build-temp-system/m4.md
  docs/build-temp-system/ncurses.md
  docs/cross-toolchain/binutils.md
  docs/cross-toolchain/gcc.md
  docs/misc/_template.md
  docs/prepare/set-env.md
Labels: enhancement

#216 zlib-ng and bz2
  docs/_sidebar.md
  docs/build-system/bz2.md
  docs/build-system/zlib.md
Labels: don`t merge

#296 Update LinuxStructure1.md
  docs/additional/LinuxStructure1.md
Labels: bug
